### ISSUE TITLE
Transition To Using Conda on Travis CI

### ISSUE THREAD

**Issue by John-P** [TIA-Lab/tiatoolbox#6]
We are currently using a conda yaml file to set up the build environment for Read The Docs but apt install command with pip requirements file on Travis CI. I suggest moving to using conda for both Read The Docs and Travis. This way we have one less thing to maintain. We currently have these places where we define dependencies:

1. A conda yaml file (this currently includes all requirements and dev requirements)
2. A windows specific conda yaml file (this currently includes all requirements and dev requirements)
3. A requirements_dev.txt (not sure if we need this anymore if moving to conda for automated builds)
4. The three requirments lists in setup.py for PyPi (just those requirements needed for the module to function and which can be installed through pip).

See [Using Conda with Travis CI](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html) for more.

Edit: Typo fixes

**Comment by John-P** [comment]
@shaneahmed  I think this is resolved now. Can I close the issue?

**Comment by shaneahmed** [comment]
> @shaneahmed I think this is resolved now. Can I close the issue?

This was not resolved as there were some issues resolving the environment. In #26 I have used tox-conda, which could be used to close this issue and merge the branch.

**Comment by shaneahmed** [comment]
Can we mark it as resolved now as it is updated on develop
